######################################################################
# Automatically generated by qmake (3.0) to 27. dec 10:47:19 2012
######################################################################

TEMPLATE = app
TARGET = imgmerger
DEPENDPATH += . src
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += src/mainwindow.h src/MultiImage.h src/imageViewer.h
FORMS += src/mainwindow.ui
SOURCES += src/main.cpp src/mainwindow.cpp src/MultiImage.cpp src/imageViewer.cpp
